### PR TITLE
Upgrade to golangci-lint v1.53.3

### LINKED ISSUE #232: Update golangci
Currently, the project is using `v1.49.0` which is quite outdated and is not aligned with the version used by other projects in the ecosystem such as `k6` and `xk6`

### PR DESCRIPTION
**Pull request by roobre**
# Description

Fixes #232 

# Checklist:

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.   
- [x] I have run linter locally (`make lint`) and all checks pass.
- [x] I have run tests locally (`make test`) and all tests pass.
- [ ] I have run relevant e2e test locally (`make e2e-xxx` for `agent`, `disruptors`, `kubernetes` or `cluster` related changes)
- [ ] Any dependent changes have been merged and published in downstream modules<br>

### CODE REVIEW

**Comment by pablochacin** [comment]
Running locally fails:
```sh
make lint
docker run --rm -v /home/pablo/go/src/github.com/grafana/xk6-disruptor:/disruptor -w /disruptor golangci/golangci-lint:v1.53.3 golangci-lint run
level=warning msg="[runner] Can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1"
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1\n\n"
make: *** [Makefile:45: lint] Error 3
```

**Comment by roobre** [comment]
@pablochacin Interesting, I thought this issue was on my end due to my source tree not being readable by others. The root cause is that git refuses to run on directories that it doesn't own. This did not happen in the past, so my best guess is that the updated docker image also updates git.

I'll check to see if there's a workaround.

**Comment by roobre** [comment]
@pablochacin I've added a workaround in https://github.com/grafana/xk6-disruptor/pull/258/commits/377f57125e187f8085982d5edc4688e8160c2820. The issue in play is a bit obscure, I've added an extended explanation in the commit message. LMK if it seems clear, or if you have concerns with it.

**Review by pablochacin — APPROVED** [review]
LGTM

**Pull request merged**
