### PR TITLE
ci: add codespell

### PR DESCRIPTION
**Pull request by roobre**
# Description

This PR adds the (in my opinion) neat [codespell action](https://github.com/codespell-project/actions-codespell) that checks for and suggest fixes for common spelling mistakes. It also fixes a few of those that codespell already found.

# Checklist:

- [ ] My code follows the coding style of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.   
- [ ] Any dependent changes have been merged and published in downstream modules<br>

### CODE REVIEW

**Comment by pablochacin** [comment]
@roobre I like the idea of automating the spelling checking as we (mostly me) have not been doing a great job there, as you have realized. 

However, I'm more in the line of activating the misspelled linter than adding a new action because we already have the linter action, and second, it makes it easier to check and fix locally using the `make lint` target in the project's makefile.

**Comment by roobre** [comment]
@pablochacin I'm fine with a different tool, I went with this on a first try because it's the one I'm familiar with.

I'll give the one you suggest a try and go for that unless there is any big drawback w.r.t. codespell. Being able to run it locally is alsoa big plus for me.

**Comment by roobre** [comment]
@pablochacin I'm giving this a swing but I don't think it's working particularly well. Turns out the `misspell` linter is, in fact, already enabled as per: https://github.com/grafana/xk6-disruptor/blob/82966c36a40cbb7ab37ef35e5236a931e03ca9e6/.golangci.yml#L72

But it does not seem to be extremely good at doing what it's supposed to do. It does work though, if you input a word from https://github.com/golangci/misspell/blob/master/words.go it will flag it, but coverage does not seem as good as codespell.

I've messed around a bit with the codespell action and it seems possible, while not very elegant, to run it locally with something like:

```shell
docker run -v `realpath .`:/disruptor -w /disruptor --entrypoint codespell ghcr.io/codespell-project/actions-codespell/stable:v2 --config .codespellrc
```

So perhaps a good option here wold be to add this command to a make target or similar.

**Review by pablochacin — APPROVED** [review]
LGTM

**Pull request merged**
